/*
 * Describe your servers and the sites they host here.
 *
 * Everything on the dashboard is generated from this file, so adding a
 * server or a site is just adding an object below. The numbers only drive
 * the simulator — once real metrics are wired in (see README), most of the
 * tuning fields go away and only names/specs remain.
 *
 * Site fields
 *   baseRps        typical requests per second at a "1.0" hour
 *   curve          24 multipliers, one per hour of the day (0 = midnight)
 *   cpuMsPerReq    CPU time one request costs on this server
 *   kbPerReq       average response size
 *   ramBaseMB      memory the app uses when idle
 *   ramPerRpsMB    extra memory per request/second of load
 *   latencyMs      response time when the server is not busy
 *   visitorsPerRps how many people online produce 1 request/second
 *   paths          example requests used for the live request log
 */
window.TRAFFIC_CONFIG = {
  // Simulated clock starts just before the lunch rush.
  startHour: 11.6,

  servers: [
    {
      id: "pi",
      name: "Server 1",
      hardware: "Raspberry Pi 4",
      kind: "pi",
      cores: 4,
      ramMB: 4096,
      netMbps: 100,
      idleCpu: 4,
      idleRamMB: 520,
      tempIdle: 42,
      tempMax: 78,
      tempWarn: 70,
      tempCrit: 80,
      sites: [
        {
          id: "chess",
          name: "Chess",
          domain: "chess.example.com",
          baseRps: 7,
          curve: [0.5, 0.35, 0.25, 0.2, 0.2, 0.25, 0.35, 0.5, 0.6, 0.65, 0.7, 0.8,
                  0.95, 0.9, 0.85, 0.9, 1.0, 1.15, 1.3, 1.45, 1.6, 1.55, 1.2, 0.8],
          cpuMsPerReq: 95,
          kbPerReq: 45,
          ramBaseMB: 210,
          ramPerRpsMB: 14,
          latencyMs: 38,
          visitorsPerRps: 9,
          paths: ["GET /", "GET /play", "POST /api/move", "POST /api/move", "GET /puzzles/daily",
                  "GET /leaderboard", "GET /game/48213", "POST /api/move", "GET /static/board.svg"],
        },
        {
          id: "school",
          name: "School",
          domain: "school.example.com",
          baseRps: 5,
          curve: [0.05, 0.03, 0.02, 0.02, 0.03, 0.08, 0.3, 0.9, 1.5, 1.6, 1.5, 1.4,
                  1.2, 1.4, 1.3, 1.0, 0.8, 0.7, 0.75, 0.8, 0.7, 0.45, 0.2, 0.1],
          cpuMsPerReq: 115,
          kbPerReq: 120,
          ramBaseMB: 340,
          ramPerRpsMB: 22,
          latencyMs: 55,
          visitorsPerRps: 14,
          paths: ["GET /", "GET /timetable", "GET /homework", "POST /homework/submit",
                  "GET /news", "GET /lunch-menu", "GET /grades", "GET /files/worksheet.pdf"],
        },
        {
          id: "restaurant",
          name: "Restaurant",
          domain: "restaurant.example.com",
          baseRps: 3,
          curve: [0.05, 0.02, 0.02, 0.02, 0.02, 0.05, 0.1, 0.2, 0.3, 0.45, 0.7, 1.4,
                  2.2, 1.6, 0.7, 0.5, 0.7, 1.2, 1.9, 2.1, 1.5, 0.8, 0.35, 0.15],
          cpuMsPerReq: 70,
          kbPerReq: 260,
          ramBaseMB: 150,
          ramPerRpsMB: 10,
          latencyMs: 42,
          visitorsPerRps: 16,
          paths: ["GET /", "GET /menu", "GET /menu", "POST /reservations", "GET /hours",
                  "GET /img/pizza.jpg", "POST /order", "GET /contact"],
        },
      ],
    },
    {
      id: "pc",
      name: "Server 2",
      hardware: "Desktop PC",
      kind: "pc",
      cores: 8,
      ramMB: 16384,
      netMbps: 1000,
      idleCpu: 6,
      idleRamMB: 2400,
      tempIdle: 36,
      tempMax: 74,
      tempWarn: 80,
      tempCrit: 90,
      sites: [
        {
          id: "checkers",
          name: "Checkers",
          domain: "checkers.example.com",
          baseRps: 9,
          curve: [0.6, 0.45, 0.35, 0.3, 0.3, 0.35, 0.45, 0.55, 0.65, 0.7, 0.75, 0.85,
                  0.95, 0.9, 0.9, 0.95, 1.05, 1.15, 1.3, 1.4, 1.45, 1.4, 1.1, 0.8],
          cpuMsPerReq: 28,
          kbPerReq: 38,
          ramBaseMB: 380,
          ramPerRpsMB: 18,
          latencyMs: 18,
          visitorsPerRps: 8,
          paths: ["GET /", "GET /play", "POST /api/move", "POST /api/move", "GET /rules",
                  "GET /lobby", "GET /game/9921", "POST /api/jump"],
        },
        {
          id: "photos",
          name: "Photo Gallery",
          domain: "photos.example.com",
          baseRps: 4,
          curve: [0.4, 0.25, 0.15, 0.1, 0.1, 0.15, 0.3, 0.5, 0.6, 0.65, 0.7, 0.8,
                  0.9, 0.85, 0.8, 0.85, 0.95, 1.1, 1.3, 1.5, 1.6, 1.45, 1.0, 0.65],
          cpuMsPerReq: 140,
          kbPerReq: 1400,
          ramBaseMB: 900,
          ramPerRpsMB: 60,
          latencyMs: 85,
          visitorsPerRps: 6,
          paths: ["GET /albums", "GET /photo/IMG_2231.jpg", "GET /photo/IMG_2232.jpg",
                  "GET /thumbs/beach.webp", "POST /upload", "GET /albums/summer-2026",
                  "GET /photo/IMG_0042.jpg"],
        },
        {
          id: "gameapi",
          name: "Game API",
          domain: "api.example.com",
          baseRps: 22,
          curve: [1.0, 0.8, 0.6, 0.45, 0.35, 0.3, 0.35, 0.45, 0.5, 0.55, 0.6, 0.7,
                  0.8, 0.8, 0.85, 0.95, 1.1, 1.25, 1.4, 1.55, 1.7, 1.75, 1.6, 1.3],
          cpuMsPerReq: 14,
          kbPerReq: 4,
          ramBaseMB: 600,
          ramPerRpsMB: 6,
          latencyMs: 9,
          visitorsPerRps: 1.5,
          paths: ["POST /v1/state", "GET /v1/match/771", "POST /v1/state", "GET /v1/players/online",
                  "POST /v1/heartbeat", "POST /v1/heartbeat", "GET /v1/ranking"],
        },
      ],
    },
    {
      id: "laptop",
      name: "Server 3",
      hardware: "Old laptop",
      kind: "laptop",
      cores: 2,
      ramMB: 8192,
      netMbps: 100,
      idleCpu: 5,
      idleRamMB: 1300,
      tempIdle: 46,
      tempMax: 82,
      tempWarn: 80,
      tempCrit: 90,
      sites: [
        {
          id: "blog",
          name: "Blog",
          domain: "blog.example.com",
          baseRps: 2.5,
          curve: [0.2, 0.15, 0.1, 0.1, 0.1, 0.2, 0.5, 1.1, 1.5, 1.4, 1.2, 1.1,
                  1.2, 1.1, 1.0, 0.95, 0.9, 0.9, 0.95, 1.0, 0.9, 0.7, 0.5, 0.3],
          cpuMsPerReq: 60,
          kbPerReq: 180,
          ramBaseMB: 260,
          ramPerRpsMB: 12,
          latencyMs: 60,
          visitorsPerRps: 20,
          paths: ["GET /", "GET /posts/building-a-home-server", "GET /posts/raspberry-pi-tips",
                  "GET /rss.xml", "GET /about", "POST /comments"],
        },
        {
          id: "map",
          name: "Minecraft Map",
          domain: "map.example.com",
          baseRps: 4,
          curve: [0.5, 0.3, 0.2, 0.15, 0.1, 0.1, 0.15, 0.25, 0.35, 0.4, 0.5, 0.6,
                  0.7, 0.75, 0.85, 1.0, 1.2, 1.35, 1.5, 1.6, 1.6, 1.4, 1.1, 0.8],
          cpuMsPerReq: 75,
          kbPerReq: 320,
          ramBaseMB: 1100,
          ramPerRpsMB: 30,
          latencyMs: 70,
          visitorsPerRps: 3,
          paths: ["GET /tiles/0/12/-4.png", "GET /tiles/0/13/-4.png", "GET /tiles/1/6/-2.png",
                  "GET /players.json", "GET /", "GET /markers.json"],
        },
      ],
    },
  ],
};
